/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
      },
      colors: {
        'rag-on-secondary-container': '#fefcff',
        'rag-on-error-container': '#93000a',
        'rag-surface-container-low': '#f2f4f6',
        'rag-primary': '#004ac6',
        'rag-surface-container': '#eceef0',
        'rag-tertiary-fixed': '#6ffbbe',
        'rag-surface': '#f7f9fb',
        'rag-error': '#ba1a1a',
        'rag-on-background': '#191c1e',
        'rag-on-surface-variant': '#434655',
        'rag-tertiary-container': '#007d55',
        'rag-on-primary-container': '#eeefff',
        'rag-primary-fixed-dim': '#b4c5ff',
        'rag-on-secondary-fixed-variant': '#004395',
        'rag-inverse-primary': '#b4c5ff',
        'rag-secondary': '#0058be',
        'rag-on-secondary': '#ffffff',
        'rag-inverse-on-surface': '#eff1f3',
        'rag-secondary-container': '#2170e4',
        'rag-on-primary-fixed': '#00174b',
        'rag-surface-variant': '#e0e3e5',
        'rag-on-surface': '#191c1e',
        'rag-primary-fixed': '#dbe1ff',
        'rag-surface-tint': '#0053db',
        'rag-on-primary': '#ffffff',
        'rag-on-tertiary-fixed': '#002113',
        'rag-outline': '#737686',
        'rag-error-container': '#ffdad6',
        'rag-surface-container-highest': '#e0e3e5',
        'rag-on-secondary-fixed': '#001a42',
        'rag-tertiary-fixed-dim': '#4edea3',
        'rag-on-primary-fixed-variant': '#003ea8',
        'rag-on-tertiary': '#ffffff',
        'rag-secondary-fixed': '#d8e2ff',
        'rag-surface-container-high': '#e6e8ea',
        'rag-surface-dim': '#d8dadc',
        'rag-on-tertiary-container': '#bdffdb',
        'rag-surface-bright': '#f7f9fb',
        'rag-on-error': '#ffffff',
        'rag-surface-container-lowest': '#ffffff',
        'rag-secondary-fixed-dim': '#adc6ff',
        'rag-inverse-surface': '#2d3133',
        'rag-outline-variant': '#c3c6d7',
        'rag-on-tertiary-fixed-variant': '#005236',
        'rag-background': '#f7f9fb',
        'rag-tertiary': '#006242',
        'rag-primary-container': '#2563eb',
        primary: {
          50: '#f0f5ff',
          100: '#d9e2ff',
          200: '#bcceff',
          300: '#b0c6ff',
          400: '#1d59c1',
          500: '#0f52ba',
          600: '#00419c',
          700: '#003c90',
          800: '#002a66',
          900: '#001945',
          950: '#00102e',
        },
        secondary: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#97f3b5',
          300: '#7ed99e',
          400: '#34d399',
          500: '#2e8b57',
          600: '#006d3d',
          700: '#00522d',
          800: '#00381e',
          900: '#00210f',
        },
        accent: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#97f3b5',
          300: '#7ed99e',
          400: '#34d399',
          500: '#2e8b57',
          600: '#006d3d',
          700: '#00522d',
          800: '#00381e',
          900: '#00210f',
        },
        surface: {
          DEFAULT: '#f9f9ff',
          dim: '#cfdaf2',
          bright: '#f9f9ff',
          lowest: '#ffffff',
          low: '#f0f3ff',
          container: '#e7eeff',
          high: '#dee8ff',
          highest: '#d8e3fb',
          dark: '#111c2d',
        },
      },
      spacing: {
        'rag-sidebar-width': '320px',
        'rag-stack-md': '1rem',
        'rag-stack-sm': '0.5rem',
        'rag-gutter': '1.5rem',
        'rag-container-max': '1440px',
        'rag-stack-lg': '2rem',
        'container-margin': '20px',
        'touch-target': '48px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
      },
      fontFamily: {
        'rag-body-sm': ['Inter'],
        'rag-headline-lg': ['Inter'],
        'rag-label-caps': ['Inter'],
        'rag-code-sm': ['JetBrains Mono'],
        'rag-body-md': ['Inter'],
        'rag-headline-md': ['Inter'],
        'rag-body-lg': ['Inter'],
        'sans': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'rag-body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'rag-headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'rag-label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'rag-code-sm': ['13px', { lineHeight: '20px', fontWeight: '450' }],
        'rag-body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'rag-headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'rag-headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'rag-body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(15, 82, 186, 0.12)',
        'glass-dark': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
        glow: '0 0 20px rgba(46, 139, 87, 0.3)',
        'glow-primary': '0 0 25px rgba(15, 82, 186, 0.25)',
        'fixnow-card': '0 4px 20px rgba(17, 28, 45, 0.05)',
        'fixnow-floating': '0 12px 40px rgba(15, 82, 186, 0.12)',
      },
      borderRadius: {
        'fixnow-sm': '0.25rem',
        'fixnow': '0.5rem',
        'fixnow-md': '0.75rem',
        'fixnow-lg': '1rem',
        'fixnow-xl': '1.5rem',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
    },
  },
  plugins: [],
};
